version: 2

updates:

  - package-ecosystem: npm
    directory: "/src/Web"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/src/Showcase.Api"
    schedule:
      interval: weekly
