services:
  api:
    build:
      context: ./src/Showcase.Api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      OTEL_SERVICE_NAME: azure-kubernetes-showcase
    ports:
      - "5080:8080"
    restart: unless-stopped

  web:
    build:
      context: ./src/Web
    ports:
      - "5173:8080"
    depends_on:
      - api
