apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: care-portal-api
  namespace: showcase
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: care-portal-api
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: community-hub-api
  namespace: showcase
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: community-hub-api
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: security-radar
  namespace: showcase
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: security-radar
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
