apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api.yaml
  - web.yaml
  - networkpolicy.yaml
  - workload-identity.yaml
  - apps/care-portal-deployment.yaml
  - apps/community-hub-deployment.yaml
patches:
  - path: namespace.yaml
    target:
      kind: Namespace
      name: showcase
