apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: showcase

resources:
  - namespace.yaml
  - workload-identity.yaml
  - api.yaml
  - web.yaml
  - apps/care-portal-deployment.yaml
  - apps/community-hub-deployment.yaml
  - apps/security-radar-deployment.yaml
  - networkpolicy.yaml
  - networking/gateway.yaml
  - networking/routes.yaml
  - networking/security-radar-route.yaml
  - networking/cert-manager.yaml

images:
  - name: azure-kubernetes-showcase-api
    newName: acrshowcasedev.azurecr.io/showcase-api
  - name: azure-kubernetes-showcase-web
    newName: acrshowcasedev.azurecr.io/showcase-web
  - name: acrshowcase.azurecr.io/care-portal-api
    newName: acrshowcasedev.azurecr.io/care-portal-api
  - name: acrshowcase.azurecr.io/community-hub-api
    newName: acrshowcasedev.azurecr.io/community-hub-api
